"""Markdown report export."""

from __future__ import annotations

from pathlib import Path

from verdictcore.models.result import DecisionResult


def export_markdown(result: DecisionResult, path: str | Path | None = None) -> str:
    lines: list[str] = []

    # Header
    lines.append("# VerdictCore Decision Report")
    lines.append("")
    lines.append(f"**Decision ID:** `{result.decision_id}`")
    lines.append(f"**Domain:** {result.domain}")
    lines.append(f"**Status:** {result.status.value}")
    lines.append("")

    # Question
    lines.append("## Question")
    lines.append("")
    lines.append(f"> {result.question}")
    lines.append("")

    # Recommendation
    lines.append("## Recommendation")
    lines.append("")
    if result.recommendation.selected_alternative_name:
        lines.append(
            f"**Selected:** {result.recommendation.selected_alternative_name} "
            f"(confidence: {result.recommendation.confidence:.2f})"
        )
    else:
        lines.append(f"**No selection made.** Status: {result.status.value}")
    lines.append("")

    # Rankings
    lines.append("## Rankings")
    lines.append("")
    lines.append("| Rank | Alternative | Score | Status |")
    lines.append("|------|-------------|-------|--------|")
    for r in result.rankings:
        rank_str = str(r.rank) if r.rank else "—"
        status = "BLOCKED" if r.blocked else "✓"
        if r.warnings:
            status = "⚠️ " + "; ".join(r.warnings)
        lines.append(f"| {rank_str} | {r.name} | {r.total_score:.1f} | {status} |")
    lines.append("")

    # Constraint Results (failures only)
    failed_constraints = [cr for cr in result.constraint_results if not cr.passed]
    if failed_constraints:
        lines.append("## Constraint Violations")
        lines.append("")
        for cr in failed_constraints:
            lines.append(
                f"- **{cr.alternative_name}**: `{cr.field}` {cr.operator} {cr.required_value} "
                f"(actual: {cr.actual_value}) → {cr.action}"
            )
            if cr.message:
                lines.append(f"  - {cr.message}")
        lines.append("")

    # Explanation
    lines.append("## Explanation")
    lines.append("")
    lines.append("### Why Selected")
    lines.append("")
    lines.append(result.explanation.why_selected)
    lines.append("")

    if result.explanation.top_drivers:
        lines.append("### Top Drivers")
        lines.append("")
        for driver in result.explanation.top_drivers:
            lines.append(f"- **{driver.criterion}**: impact {driver.impact:.2f}")
        lines.append("")

    if result.explanation.why_not:
        lines.append("### Why Not")
        lines.append("")
        for wn in result.explanation.why_not:
            lines.append(f"- **{wn.alternative_name}**: {wn.reason}")
        lines.append("")

    # Sensitivity
    if result.explanation.sensitivity:
        sens = result.explanation.sensitivity
        lines.append("## Decision Stability")
        lines.append("")
        lines.append(f"- **Score:** {sens.decision_stability_score:.2f}")
        lines.append(f"- **Level:** {sens.level}")
        if sens.sensitive_to:
            lines.append(f"- **Sensitive to:** {', '.join(sens.sensitive_to)}")
        lines.append("")

    # Audit
    lines.append("## Audit Trail")
    lines.append("")
    lines.append(f"- **Engine version:** {result.audit.engine_version}")
    lines.append(f"- **Policy version:** {result.audit.policy_version}")
    lines.append(f"- **Input hash:** `{result.audit.input_hash}`")
    lines.append(f"- **Ruleset hash:** `{result.audit.ruleset_hash}`")
    lines.append(f"- **Output hash:** `{result.audit.output_hash}`")
    lines.append(f"- **Created at:** {result.audit.created_at.isoformat()}")
    lines.append("")

    # Warnings
    if result.warnings:
        lines.append("## Warnings")
        lines.append("")
        for w in result.warnings:
            lines.append(f"- {w}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by VerdictCore*")
    lines.append("")

    markdown = "\n".join(lines)

    if path:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(markdown, encoding="utf-8")

    return markdown
